//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIWEB_UMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_solicitudEntrega
    {
        public int Id_Entrega { get; set; }
        public int Persona_Envio { get; set; }
        public int Tipo_Paquete { get; set; }
        public string Descripcion_Paquete { get; set; }
        public string Peso_Paquete { get; set; }
        public int Persona_Recibe { get; set; }
        public int Direccion_Entrega { get; set; }
        public int Ubicacion_Entrega { get; set; }
        public decimal Pago { get; set; }
    
        public virtual tbl_direccion tbl_direccion { get; set; }
        public virtual tbl_envio tbl_envio { get; set; }
        public virtual tbl_paquete tbl_paquete { get; set; }
        public virtual tbl_persona tbl_persona { get; set; }
        public virtual tbl_recibe tbl_recibe { get; set; }
    }
}
