//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIWEB_UMG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntregaEntities : DbContext
    {
        public EntregaEntities()
            : base("name=EntregaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_direccion> tbl_direccion { get; set; }
        public virtual DbSet<tbl_envio> tbl_envio { get; set; }
        public virtual DbSet<tbl_paquete> tbl_paquete { get; set; }
        public virtual DbSet<tbl_persona> tbl_persona { get; set; }
        public virtual DbSet<tbl_recibe> tbl_recibe { get; set; }
        public virtual DbSet<tbl_solicitudEntrega> tbl_solicitudEntrega { get; set; }
        public virtual DbSet<tbl_tipoPersona> tbl_tipoPersona { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    }
}
