//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIWEB_UMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_direccion()
        {
            this.tbl_envio = new HashSet<tbl_envio>();
            this.tbl_solicitudEntrega = new HashSet<tbl_solicitudEntrega>();
        }
    
        public int Id_Direccion { get; set; }
        public Nullable<int> No_Casa { get; set; }
        public string Calle { get; set; }
        public string Avenida { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Departamento { get; set; }
        public string Pais { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_envio> tbl_envio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_solicitudEntrega> tbl_solicitudEntrega { get; set; }
    }
}
